name: Keep API Alive

on:
  schedule:
    # Ping every 2 minutes for testing
    - cron: '*/2 * * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping API Health Endpoint
        run: |
          echo "Pinging API to keep alive..."
          curl -f https://django-auth-service-1z64.onrender.com/health/ || echo "Ping failed"
          echo "Ping completed at $(date)"